version: '3'
services:
  medexuk:
    build: .
    ports:
      - "1000:1000"
    depends_on: # other containers it needs in order to run
      - databaseuk
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=databaseuk
    volumes:
      - ./import:/app/import
    restart: always

  databaseuk:
    image: postgres
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always



