version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on: # other containers it needs in order to run
      - database
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
    volumes:
      - ./import:/app/import
    restart: always
  database:
#    timescaledb:
#      image: timescale/timescaledb:latest-pg12
    image: postgres #if using an existing image
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    restart: always
volumes:
  database-data: # named volumes can be managed easier using docker-compose



