version: '3'
services:
  medex3:
    build: .
    ports:
      - "900:900"
    depends_on: # other containers it needs in order to run
      - database3
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database3
    volumes:
      - ./import:/app/import
    restart: always

  database3:
    image: postgres
    ports:
      - "5429:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always



