version: '3'
services:
  medex:
    image: aljoschak1/medex
    build: .
    ports:
      - "80:80"
    depends_on: # other containers it needs in order to run
      - database
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
    volumes:
      - ./import:/app/import
    restart: always

  database:
    image: postgres
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always



