version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on: # other containers it needs in order to run
      - database
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
    volumes:
      - ./import:/app/import
    restart: always
  database:
    image: postgres #if using an existing image
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=example
    restart: always




