version: '3.6'
services:
  medex:
    image: aljoschak1/medex
    container_name: medex
    build: .
    ports:
      - "8000:8000"
    depends_on: # other containers it needs in order to run
      - database_medex
    environment:
      - EXPRESS_MEDEX_MEDDUSA_URL=http://localhost:3500
      - MEDDUSA_URL=http://localhost:3000
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database_medex
    volumes:
      - ./import:/app/import
    restart: always


  database_medex:
    image: postgres
    container_name: database_medex
    shm_size: 1g
    ports:
      - "127.0.0.1:5429:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=example
    restart: always

networks:
  express-medex-meddusa-network:
    external: true




